#!/bin/sh

# uninstall.sh 0 -> do not save configuration

PulseDir="/Library/Application Support/Pulse Secure/Pulse"
BrandingDir="/Library/Application Support/Pulse Secure/PulseBranding"
UninstallDir="/Library/Application Support/Pulse Secure/Pulse/Uninstall.app/Contents/Resources"
FirewallKext="/Library/Extensions/PulseSecureFirewall.kext"

SaveConfig=1	#default to save configuration
if [ "$#" -gt 0 ]; then
    SaveConfig=$1   # 1st argument
fi

/usr/bin/osascript << EOF
if application "Pulse Secure" is running then
        tell application "Pulse Secure"
                do PulseMainUI command "QUITPULSEUI"
        end tell
end if
EOF
sleep 2    # wait for 2 seconds to quit Pulse UI gracefully

PULSEUI_PID=`ps -xalwwww|grep \[A\]pplications\/Pulse\ Secure.app\/Contents\/MacOS\/Pulse\ Secure |awk '{print $2}'`
if [ ! "$PULSEUI_PID" = "" ]; then
    echo "Quit Pulse UI: $PULSEUI_PID" >> "$PulseDir/uninstall.log"
    kill -9 $PULSEUI_PID
fi

# unload tray for all other logged in Users
        for userName in `/usr/bin/users`
        do 
               	echo "Unload Pulse Tray for $userName" >> "$PulseDir/uninstall.log"
                su -l $userName -c  "launchctl unload -S Aqua /Library/LaunchAgents/net.pulsesecure.pulsetray.plist"
        done

if [ -f /Library/LaunchAgents/com.pulsesecure.pulsetray.plist ]; then
sudo rm -rf /Library/LaunchAgents/com.pulsesecure.pulsetray.plist
fi

if [ -f /Library/LaunchAgents/net.pulsesecure.pulsetray.plist ]; then
sudo rm -rf /Library/LaunchAgents/net.pulsesecure.pulsetray.plist
fi

echo "Unload /Library/LaunchDaemons/net.pulsesecure.AccessService.plist" >> "$PulseDir/uninstall.log"
if [ -f /Library/LaunchDaemons/net.pulsesecure.AccessService.plist ]; then
    sudo launchctl unload /Library/LaunchDaemons/net.pulsesecure.AccessService.plist
    sudo rm -rf /Library/LaunchDaemons/net.pulsesecure.AccessService.plist
fi

echo "Unload $FirewallKext" >> "$PulseDir/uninstall.log"
if [ -d  "$FirewallKext" ]; then
    sudo kextunload "$FirewallKext"
fi

RscDir="$( cd "$( dirname "$0" )" && pwd )"

echo "Remove semaphore /var/log/Pulse Secure/Logging" >> "$PulseDir/uninstall.log"
sudo "$RscDir"/sem_delete.pl "/var/log/Pulse Secure/Logging/"

echo "Remove $PulseDir/Uninstall.app" >> "$PulseDir/uninstall.log"
sudo rm -rf "$PulseDir"/Uninstall.app
echo "Remove $BrandingDir" >> "$PulseDir/uninstall.log"
sudo rm -rf "$BrandingDir"

if [ "$SaveConfig" -ne 1 ]; then
    echo "Remove Pulse configuration" >> "$PulseDir/uninstall.log"
    sudo rm -f "$PulseDir"/*.dat
    sudo rm -f "$PulseDir"/*.bak
    sudo rm -f "$PulseDir"/*.tmp
    sudo rm -f "$PulseDir"/DeviceId
fi

echo "Forget packages..." >> "$PulseDir/uninstall.log"
sudo pkgutil --forget net.pulsesecure.PulsePreflight.pkg
sudo pkgutil --forget net.pulsesecure.JUNS.pkg
sudo pkgutil --forget net.pulsesecure.JamUI.pkg
sudo pkgutil --forget net.pulsesecure.ConnectionStore.pkg
sudo pkgutil --forget net.pulsesecure.ConnectionManager.pkg
sudo pkgutil --forget net.pulsesecure.eapService.pkg
sudo pkgutil --forget net.pulsesecure.dsTMService.pkg
sudo pkgutil --forget net.pulsesecure.iveConnectionMethod.pkg
sudo pkgutil --forget net.pulsesecure.TnccPlugin.pkg
sudo pkgutil --forget net.pulsesecure.TMPostflight.pkg
sudo pkgutil --forget net.pulsesecure.TnccPostflight.pkg
sudo pkgutil --forget net.pulsesecure.vpnAccessMethod.pkg
sudo pkgutil --forget net.pulsesecure.PulsePostflight.pkg
sudo pkgutil --forget net.pulsesecure.CorePostflight.pkg
sudo pkgutil --forget net.pulsesecure.UACNCPostflight.pkg
sudo pkgutil --forget net.pulsesecure.PulseSecureFirewall.pkg
# forget more packages

if [ -d "/Applications/Pulse Secure.app" ]; then
  echo "Remove /Applications/Pulse Secure.app" >> "$PulseDir/uninstall.log"
  sudo rm -rf "/Applications/Pulse Secure.app"
fi

if [ -d "$FirewallKext" ]; then
    echo "Remove $FirewallKext" >> "$PulseDir/uninstall.log"
    sudo rm -rf "$FirewallKext"
fi

if [ -d "/Applications/Junos Pulse.app" ]; then
  echo "Remove /Applications/Junos Pulse.app" >> "$PulseDir/uninstall.log"
  sudo rm -rf "/Applications/Junos Pulse.app"
fi

#Obtain console username
ConsoleUsername=`stat -f "%Su" /dev/console`
if [ -d "/Users/$ConsoleUsername/.Trash/Pulse Secure.app" ]; then
   echo "Remove /Users/$ConsoleUsername/.Trash/Pulse Secure.app" >> "$PulseDir/uninstall.log"
   sudo rm -rf "/Users/$ConsoleUsername/.Trash/Pulse Secure.app";
   echo "Remove /Users/$ConsoleUsername/.Trash/PulseSecureFirewall.kext" >> "$PulseDir/uninstall.log"
   sudo rm -rf "/Users/$ConsoleUsername/.Trash/PulseSecureFirewall.kext";
fi

echo "Remove /Library/LaunchDaemons/net.pulsesecure.UninstallPulse.plist" >> "$PulseDir/uninstall.log"
sudo unlink /Library/LaunchDaemons/net.pulsesecure.UninstallPulse.plist

exit 0
